### ISSUE TITLE
typos error  in fallback and typos error in owner sender

### ISSUE THREAD

**Issue by ethereumbigvena** [halls7588/Code-for-the-6-Steps-to-ERC20-Tokens-and-ICO-Smart-Contracts-Tutorial#2]
hello sir 
i got error in specific line in online remix editior

**Comment by halls7588** [comment]
The code was written in a lower version of Solidity then the current
version. Lower the version of solidity being compiled to 0.4.23 and it will
work fine.

**Comment by ethereumbigvena** [comment]
hello 
when i connect metamask to myetherwallet 
contract is  not deploying due to byte code error
